spring.application.name=import-control

server.port=${PORT:8080}

api.security.token.secret=${JWT_SECRET:senhasecreta}
api.security.cors.origins=${CORS_ORIGINS:http://localhost:5173}


spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect