spring.application.name=import-control
server.port=${PORT:8080}

api.security.token.secret=${JWT_SECRET:senhasecreta}

# Datasource
spring.datasource.url=jdbc:postgresql://ep-purple-paper-aizge2h3-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_WLTixEufOr95
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=true

